services:

  gateway:
    build: ./gateway
    container_name: gateway
    ports:
      - "8080:8080"
    depends_on:
      - server
    environment:
      - SERVER_PORT=8080
      - SERVER_URL=http://server:9090

  server:
    build: ./server
    container_name: server
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - DB_HOTS=db
      - DB_PORT=5432
      - DB_NAME=later
      - POSTGRES_USER=rootLater
      - POSTGRES_PASSWORD=rootLater
      - SERVER_PORT=9090
    restart: on-failure

  db:
    image: postgres:13.7-alpine
    container_name: db
    hostname: db
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=later
      - POSTGRES_USER=rootLater
      - POSTGRES_PASSWORD=rootLater